[versions]
corePlugins = "1.0.1"
domain = "1.0.0"

[libraries]
corePlugins = { group = "vn.core.libs", name = "plugins", version.ref = "corePlugins" }
domain = { group = "vn.core.libs", name = "domain", version.ref = "domain" }

[plugins]
